import {StyleSheet} from 'react-native';
import {fonts} from 'react-native-elements/dist/config';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'rgb(44, 0, 95)',
  },
  viewss: {
    flex: 1,
    flexDirection: 'column',
    margin: 5,
  },

  touchmenu: {
    flex: 1,
    backgroundColor: '#034E6D',
    borderRadius: 30,
    // margin: 0,
    opacity: 1,
    borderColor: '#fff',
    borderWidth: 0.3,
    borderColor: 'thistle',
    borderRadius: 30,
  },
  bgfeed: {
    flex: 1,
    alignItems: 'center',
    borderTopEndRadius: 50,
    borderTopStartRadius: 50,
    opacity: 8.5,
    height: 1000,
    position: 'absolute',
    width: '100%',
    zIndex: 11,
    marginTop: 320,
    padding: 10,
    backgroundColor: '#102F3B',
  },
  imgg: {
    resizeMode: 'center',

    marginBottom: 0,
    zIndex: 0,
    position: 'relative',
    borderRadius: 10,
    width: '100%',
    height: 350,
  },
  cardss: {},
  nname1: {
    height: 80,
    backgroundColor: '#034E6D',
    // opacity:0.5,
    flexDirection: 'row',
    marginBottom: 10,
    alignItems: 'center',
    borderColor: '#fff',
    // borderWidth: 0.23,
    borderColor: 'thistle',
    borderRadius: 20,
  },
  nname: {
    flexDirection: 'column',
    marginTop: 50,
  },
  ttitles: {
    marginLeft: 10,
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  iconcss: {
    fontSize: 20,
    color: '#fff',
  },
  detail_data: {
    opacity: 1,
    fontSize: 18,
    color: '#fff',
    fontWeight: 'bold',
    marginLeft: 20,
  },
  icon1: {
    marginLeft: 30,
    width: 50,
    height: 50,
    backgroundColor: 'red',
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#fff',
    borderWidth: 0.3,
  },
  icon2: {
    marginLeft: 30,
    width: 50,
    height: 50,
    backgroundColor: '#5C00CB',
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#fff',
    borderWidth: 0.3,
  },
  icon3: {
    marginLeft: 30,
    width: 50,
    height: 50,
    backgroundColor: '#FF00E5',
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#fff',
    borderWidth: 0.3,
  },
  icon4: {
    marginLeft: 30,
    width: 50,
    height: 50,
    backgroundColor: '#000CFF',
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#fff',
    borderWidth: 0.3,
  },
});
